#!/usr/bin/env python3
"""Replay N shifts through the live loop and cache the manager / leadership views.

    python scripts/build_rollup.py --runs 15 --out results/rollup.json

Precomputed on purpose. The rollup is deterministic - the same shifts through
the same loop give the same numbers - so computing it once and serving a file
keeps the demo instant and, more importantly, makes the artefact inspectable:
every figure in the manager and leadership views can be traced to this file
and regenerated by this command.

Each run in the dataset is one shift; shifts are grouped into weeks of five.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from twin.record import Recorder                                    # noqa: E402
from twin.loop import TwinLoop                                      # noqa: E402
from twin.rollup import (rollup_shift, rollup_week, reconcile,      # noqa: E402
                         leadership_case, detection_evidence,
                         SHIFTS_PER_WEEK)

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_FLOW = os.path.join(HERE, "..", "..", "digitaltwin.ai",
                            "dataset", "v5", "flow", "runs")
RESULTS = os.path.join(HERE, "..", "results")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--flow", default=DEFAULT_FLOW)
    ap.add_argument("--runs", type=int, default=15)
    ap.add_argument("--step", type=int, default=300)
    ap.add_argument("--prefix", default="L1_run_")
    ap.add_argument("--out", default=os.path.join(RESULTS, "rollup.json"))
    a = ap.parse_args()

    if not os.path.isdir(a.flow):
        sys.exit(f"flow dir not found: {a.flow}\n"
                 f"Regenerate the dataset with scripts/build_v5.py, or pass --flow.")

    tags = sorted(d for d in os.listdir(a.flow) if d.startswith(a.prefix))[:a.runs]
    if not tags:
        sys.exit(f"no runs matching {a.prefix}* in {a.flow}")

    shifts = []
    for i, tag in enumerate(tags):
        rec = Recorder.from_dir(os.path.join(a.flow, tag), i)
        lp = TwinLoop(rec, step_s=a.step)
        frames = list(lp.frames())
        s = rollup_shift(frames, a.step)
        s["run"] = tag
        shifts.append(s)
        print(f"  [{i+1}/{len(tags)}] {tag}  units={s['units_out']:3d}  "
              f"moves={s['constraint_moves']:2d}  "
              f"constraint_min={s['constraint_minutes']:.0f}", flush=True)

    weeks = []
    for w0 in range(0, len(shifts), SHIFTS_PER_WEEK):
        chunk = shifts[w0:w0 + SHIFTS_PER_WEEK]
        wk = rollup_week(chunk)
        wk["week"] = len(weeks) + 1
        wk["runs"] = [c["run"] for c in chunk]
        weeks.append(wk)

    evidence = detection_evidence(RESULTS)
    leadership = leadership_case(shifts, weeks, evidence)
    rec_check = reconcile(shifts, weeks, leadership)

    out = {"generated_from": os.path.basename(a.flow.rstrip("/\\")),
           "n_shifts": len(shifts), "step_s": a.step,
           "shifts": shifts, "weeks": weeks,
           "leadership": leadership, "reconciliation": rec_check}

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1)

    print(f"\n{len(shifts)} shifts -> {len(weeks)} weeks")
    print(f"reconciliation: {'PASS' if rec_check['passes'] else 'FAIL'}  "
          f"({rec_check['statement']})")
    for k, v in rec_check["constraint_minutes"].items():
        print(f"    constraint_minutes  {k:22s} {v}")
    print(f"\ntop constraints, week 1:")
    for t in weeks[0]["top_constraints"][:4]:
        print(f"    {t['station']}  {t['share']:5.1f}%  ({t['minutes']:.0f} min)")
    print(f"\nwritten: {a.out}")


if __name__ == "__main__":
    main()
