#!/usr/bin/env python3
"""
Build v6 — the segmented 40-station dataset (Sagar's local draft).

Status: NOT reviewed by Priyansh. layouts.py/plant.py changes are additive
and opt-in (segment=None on L1-L4, so those are unchanged - verified via
`pytest tests/` giving the same 10 passed / 1 known-failed as before this
file existed). This script itself is new, touches nothing in build_v5.py,
and dataset/v5/ is untouched.

Built in response to two things landing the same day:
  - PROGRESS.md Workstream D's own stated gate: "40 stations"
    (L1-L4 top out at 30 - see layouts.LAYOUTS["L2"])
  - Priyansh's suggestion #8 and his Part A write-up (2026-08-25):
    segments should behave differently, and sensor coverage should vary
    BY SEGMENT, not just station count going up

Layout: L5, 40 stations = 15 body + 10 paint + 15 final (layouts.py).
  body   - robotic, tight variance (sigma 0.05-0.09), ~90% instrumented
  paint  - wider spread, ~90% dark: one "booth" station carries an
           aggregate reading (observability 0.4) for the whole segment,
           matching Part A 1.1's "booth-level only, not per-station"
  final  - manual, CV-like sigma 0.25-0.55, ~65% dark -> covered by
           manual_check events instead of sensors (Part A 1.3)

KNOWN LIMITATIONS - stated here, not discovered later:
  - Paint's "capacity behaves differently from flow" is approximated with
    larger buffers (4-7 vs 1-3), NOT a true shared-capacity batch/oven
    resource. A real batch mechanic needs new tick-loop logic in plant.py
    and is flagged as follow-up work, not attempted here - the tick-based
    per-unit-server architecture is exactly where this project's past bugs
    (RNG desync, unpaired CRN) have come from, and this is a local draft,
    not something to gamble the simulator's correctness on.
  - The coupling map picks the nearest downstream NON-DARK station, not the
    nearest station with measured adequate detection power (Part A 1.4's
    actual proposal) - that needs a per-fault detectability study this
    script doesn't run. Documented as a simplification, not silently.
  - manual_check's NOK rate and entry_latency are a first-pass model
    (baseline ~3.4% NOK, calibrated off AI4I2020's real 3.39% machine
    failure rate - see dataset/v6_segmented/README.md), not fit to any
    genealogy-EOL cross-check yet (Part A 1.3's actual proposed test).
  - Truth labels (sensitivity/regret) are NOT generated by this script -
    that's build_truth.py's ~2-3h job and reuses LAYOUTS generically, so
    it should work on L5 once someone chooses to run it. Not run here to
    keep this a same-session deliverable.

Schema additions used (both still `open` in suggestion_by_priyansh/
SUGGESTIONS.md as of this run - built against them per Sagar's decision to
treat them as accepted for this draft):
  - manual_check event type: unit_id, station_id, check_id, result,
    reason_code, recorded_at, entry_latency
  - provenance value 'attested' on every manual_check row
"""

import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))
from twin.plant import build_plant_config, simulate_plant          # noqa: E402
from twin.layouts import LAYOUTS                                   # noqa: E402
from build_v5 import tools_for_run, corrupt_observed               # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "dataset", "v6_segmented", "flow")
FAULTS = ("degrade_ramp", "degrade_step", "station_down",
          "material_starvation", "quality_hold")

REASON_CODES = ("fixture_alignment", "missing_fastener", "cosmetic_mark",
                 "wrong_variant_part", "harness_routing")
# baseline NOK rate calibrated off AI4I2020's real machine-failure rate
# (3.39% on 10,000 real machine-cycles) - see README's calibration section
MANUAL_CHECK_BASE_NOK = 0.034


def observability_table_v6(spine, segment, vintage, dark, dropouts, booth):
    rows = []
    for i, st in enumerate(spine):
        seg = segment[i]
        if st in dark and st == booth:
            o, note = 0.4, "paint booth aggregate sensor - segment-level, not per-station"
        elif st in dark and seg == "final":
            o, note = 0.0, "no sensors - covered by manual_check only"
        elif st in dark:
            o, note = 0.0, "permanently dark - no state, no scans"
        elif st in dropouts:
            o, note = 0.55, "temporary sensor dropout during part of the shift"
        else:
            o, note = 1.0, "fully instrumented"
        rows.append(dict(station_id=st, segment=seg, vintage=vintage[i],
                         observability=o, note=note))
    return pd.DataFrame(rows)


def coupling_map(spine, dark_set):
    """For each dark station, the nearest downstream NON-dark station.

    Simplification flagged in the module docstring: 'nearest instrumented'
    stands in for Part A's actual proposal of 'nearest with MEASURED
    adequate detection power', which needs a per-fault study this script
    doesn't run.
    """
    rows = []
    n = len(spine)
    for i, st in enumerate(spine):
        if st not in dark_set:
            continue
        target, hops = None, 0
        for j in range(i + 1, n):
            hops += 1
            if spine[j] not in dark_set:
                target = spine[j]
                break
        rows.append(dict(dark_station=st, coupling_target=target or "EXIT_GATE",
                         hops=hops if target else n - i))
    return pd.DataFrame(rows)


def manual_check_events(rng, scans_full, final_dark_stations, run_tag, fault):
    """unit_id, station_id, check_id, result, reason_code, recorded_at,
    entry_latency, provenance='attested' - Part A 1.3's two proposed schema
    additions, built here since Sagar accepted both for this draft.
    """
    rows = []
    outs = scans_full[(scans_full.event == "out") &
                      (scans_full.station_id.isin(final_dark_stations))]
    for _, r in outs.iterrows():
        # confirmation-biased: NOK rate barely moves even during an active
        # fault at this station, which is Part A 1.3's actual point - a
        # checklist that always reads OK is measuring compliance with the
        # checklist, not quality. We nudge it slightly so it isn't USELESS,
        # not so it's an honest sensor.
        p_nok = MANUAL_CHECK_BASE_NOK
        if fault["idx"] >= 0 and f"S{fault['idx']+1:02d}" == r.station_id \
                and fault["onset_s"] <= r.t_s:
            p_nok = min(0.08, MANUAL_CHECK_BASE_NOK * 2.0)
        nok = rng.random() < p_nok
        latency = float(rng.lognormal(np.log(240), 0.6))  # ~4 min median
        rows.append(dict(
            run=run_tag, unit_id=r.vin, station_id=r.station_id,
            check_id=f"{r.station_id}-CHK1",
            result="NOK" if nok else "OK",
            reason_code=str(rng.choice(REASON_CODES)) if nok else "",
            recorded_at_s=round(r.t_s + latency, 1),
            entry_latency_s=round(latency, 1),
            provenance="attested"))
    return pd.DataFrame(rows)


def build_run(rid, kind, seed):
    lay = LAYOUTS["L5"]
    cfg = build_plant_config(seed, "L5", kind, 1)
    res = simulate_plant(cfg, record=True)
    rng = np.random.default_rng(seed ^ 0x5EED)
    tag = f"L5_run_{rid:03d}"

    sc = pd.DataFrame(res["scans"], columns=["vin", "station_id", "event", "t_s"])
    stt = pd.DataFrame(res["states"], columns=["station_id", "state", "t_s"])
    spine = sorted({s for s in sc.station_id.unique() if s.startswith("S")})
    dark = set(res["dark"])
    segment = lay.segment
    vintage = lay.vintage

    paint_dark = [spine[i] for i in range(len(spine))
                 if spine[i] in dark and segment[i] == "paint"]
    booth = None
    if len(paint_dark) < sum(1 for s in segment if s == "paint"):
        # the one paint station NOT marked dark is the booth aggregate sensor
        paint_all = [spine[i] for i in range(len(spine)) if segment[i] == "paint"]
        survivors = [s for s in paint_all if s not in dark]
        booth = survivors[0] if survivors else None

    final_dark = [spine[i] for i in range(len(spine))
                 if spine[i] in dark and segment[i] == "final"]

    cand = [s for s in spine if s not in dark]
    n_tools = min(len(cand), 6)
    tool_st = sorted(rng.choice(cand, n_tools, replace=False).tolist()) if cand else []
    tools, tool_truth = tools_for_run(rng, sc, tool_st, tag)

    drop_pool = [s for s in cand if s not in tool_st] or cand
    drop_st = set(rng.choice(drop_pool, min(2, len(drop_pool)), replace=False).tolist()) \
        if drop_pool else set()
    obs_sc = sc[~sc.station_id.isin(dark)].copy()
    obs_st = stt[~stt.station_id.isin(dark)].copy()
    for st in drop_st:
        a = float(rng.uniform(0.2, 0.6)) * cfg.horizon_s
        b = a + float(rng.uniform(0.1, 0.25)) * cfg.horizon_s
        obs_st = obs_st[~((obs_st.station_id == st) & (obs_st.t_s >= a) & (obs_st.t_s < b))]

    obs_sc, obs_st, tools_obs, artifacts = corrupt_observed(
        rng, obs_sc, obs_st, tools, spine)

    manual = manual_check_events(rng, sc, final_dark, tag, cfg.fault)
    coupling = coupling_map(spine, dark)

    rd = os.path.join(OUT, "runs", tag)
    hd = os.path.join(rd, "hidden")
    os.makedirs(hd, exist_ok=True)
    obs_sc.to_csv(os.path.join(rd, "unit_scan.csv"), index=False)
    obs_st.to_csv(os.path.join(rd, "station_state.csv"), index=False)
    pd.DataFrame(res["buffers"], columns=["buffer_id", "level", "capacity", "t_s"]) \
        .to_csv(os.path.join(rd, "buffer_level.csv"), index=False)
    pd.DataFrame(res["andon"], columns=["station_id", "reason", "t_s", "dur_s"]) \
        .to_csv(os.path.join(rd, "andon_log.csv"), index=False)
    pd.DataFrame(res["rework"], columns=["vin", "event", "t_s"]) \
        .to_csv(os.path.join(rd, "rework_log.csv"), index=False)
    pd.DataFrame(res["calendar"]).to_csv(os.path.join(rd, "calendar.csv"), index=False)
    if len(tools_obs):
        tools_obs.to_csv(os.path.join(rd, "tool_readings.csv"), index=False)
    if len(manual):
        manual.to_csv(os.path.join(rd, "manual_check.csv"), index=False)
    coupling.to_csv(os.path.join(rd, "coupling_map.csv"), index=False)

    sc.to_csv(os.path.join(hd, "unit_scan_full.csv"), index=False)
    stt.to_csv(os.path.join(hd, "station_state_full.csv"), index=False)
    pd.DataFrame(res["microstops"], columns=["station_id", "t_s", "dur_s"]) \
        .to_csv(os.path.join(hd, "microstops.csv"), index=False)
    if len(tool_truth):
        tool_truth.to_csv(os.path.join(hd, "tool_truth.csv"), index=False)
    artifacts.to_csv(os.path.join(hd, "artifacts.csv"), index=False)
    observability_table_v6(spine, segment, vintage, dark, drop_st, booth).to_csv(
        os.path.join(hd, "observability.csv"), index=False)
    with open(os.path.join(hd, "fault.json"), "w") as fh:
        json.dump(cfg.fault, fh)

    f = cfg.fault
    return dict(run=tag, layout="L5", seed=seed, n_shifts=1, fault_kind=kind,
                fault_station=(f"S{f['idx']+1:02d}" if f["idx"] >= 0 else ""),
                fault_onset_s=f["onset_s"], fault_magnitude=round(f["magnitude"], 3),
                fault_duration_s=f["duration_s"],
                dark_stations=";".join(sorted(dark)),
                dropout_stations=";".join(sorted(drop_st)),
                tool_stations=";".join(tool_st),
                manual_check_stations=";".join(sorted(final_dark)),
                paint_booth_station=booth or "",
                n_microstops=len(res["microstops"]),
                n_manual_checks=len(manual),
                jph=round(res["total"] / (cfg.horizon_s / 3600), 1),
                completed=res["total"], rework_visits=res["rework_visits"])


def main():
    os.makedirs(os.path.join(OUT, "runs"), exist_ok=True)
    plan = [(k, i) for k in FAULTS for i in range(2)] + [("none", i) for i in range(10)]
    man = []
    for rid, (kind, i) in enumerate(plan, start=1):
        man.append(build_run(rid, kind, 6700000 + rid))
        print(f"  ...{rid}/{len(plan)} runs ({kind})", flush=True)

    m = pd.DataFrame(man)
    m.to_csv(os.path.join(OUT, "run_manifest.csv"), index=False)
    print(f"\n{len(m)} L5 runs written to {OUT}")
    print(f"JPH  no-fault {m[m.fault_kind=='none'].jph.mean():.1f}  "
          f"faulted {m[m.fault_kind!='none'].jph.mean():.1f}")
    print(f"mean manual_check events/run: {m.n_manual_checks.mean():.0f}")
    print(f"mean dark stations/run: {m.dark_stations.apply(lambda s: len(s.split(';')) if s else 0).mean():.1f}")


if __name__ == "__main__":
    main()
